# Generated by Django 5.0.2 on 2024-02-27 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BooK",
            fields=[
                ("bookno", models.IntegerField(primary_key=True, serialize=False)),
                ("bookname", models.CharField(max_length=20)),
                ("bookprice", models.IntegerField(help_text="Enter the price of book")),
                ("quantity", models.IntegerField()),
                ("authorname", models.CharField(max_length=50)),
            ],
        ),
    ]
